---
###############################################################################
# User Specific Settings
###############################################################################

# Default root password to set - temporary, password is disabled at end.
# The non-root user account will have sudo privileges
default_root_password: "change!me"

# Define non-root usr account to create (home drive will be its own dataset)
regular_user_account: "rich"
regular_user_password: "change!me"
regular_user_fullname: "Richard Durso"
regular_user_groups: "adm,cdrom,dip,lpadmin,lxd,plugdev,sambashare,sudo"
regular_user_shell: "/bin/bash"

###############################################################################
# Computer Configuration Settings
###############################################################################

# Create Swap Paritions
enable_swap_partitions: true

# Swap partition size when a single device is used
single_swap_partition_size_MB: "4096"

# Swap partition size, per device, when multiple devices are used
# If set_boot_pool_type is mirror, then it will be a mdm mirror of this size in MB
# If set_boot_pool_type is raidz, then is will be a mdm raid5 of this size in MB (#devices-1*size_MB)
multiple_swap_partition_size_MB: "2048"

# Use Grub with UEFI (will do Grub with Legacy BIOS if false)
use_uefi_booting: true

# Full GUI installtion or command-line only environment
command_line_only: false

# Define the local pre-fix to enable in /etc/locale.gen
locale_prefix: "en_US"

# Define the timezone to be placed in /etc/timezone
timezone_value: "America/New_York"

###############################################################################
# ZFS Specific Adjustable Settings
###############################################################################

# Define the boot pool type based on number of devices.
#  - If you want 3 devices to be a 3 way mirror change it, etc.
#  - Raidz will be the default if something below is not defined.
set_boot_pool_type:
  1: ""
  2: "mirror"
  3: "raidz"
  4: "raidz"
  default: "raidz"

# Define the root pool type based on number of devices.
#  - If you want 3 devices to be a 3 way mirror change it, etc.
#  - If even number 2,4,6,8, etc of type mirror, then mirrored vdevs will be used.
#  - -  This is higher performance with redundancy and much faster resilver times
#  - -  than using any type of raidz.
#  - Raidz will be the default if something below is not defined.
#  - NOTE: A raidz2 requires 4 or more devices.
set_root_pool_type:
  1: ""
  2: "mirror"
  3: "raidz"
  4: "mirror"
  5: "raidz"
  6: "mirror"
  default: "raidz"

# Define Pool Names
boot_pool_name: "bpool"
root_pool_name: "rpool"