---
#
# This role/task will detect if Ansible is running under VirtualBox and 
# then set a variable named "virtual_box" to true or false
#
  - name: Check if lspci is installed
    ansible.builtin.stat:
      path: /usr/bin/lspci
    register: stat_lspci

# Determine if running under Virtual Box
  - name: Determine if running under Virtual Box
    block:
      - name: Checking lspci device list
        command: "lspci"
        register: PCI_Devices
        
      # Under virtual box there will be a PCI device 
      - set_fact:
          virtual_box: "{{ (PCI_Devices.stdout.find('VirtualBox') == -1) |ternary(false,true) }}"

      - debug:
          msg: "VirtualBox Detected: {{virtual_box}}"

    when: 
      - ansible_os_family == "Debian" or
        ansible_os_family == "Archlinux"
      - stat_lspci.stat.exists is defined and stat_lspci.stat.exists
    tags:
      - always

  # If check not defined for OS Family above then fail.
  - fail:
      msg: "ERROR - VirtualBox Check not defined for {{ansible_os_family}}"
    when: 
      - ansible_os_family != "Debian" and
        ansible_os_family != "Archlinux"
    tags:
      - always