---
###[ Wipe Partitions of Selected Device ]######################################
- name: Wipe Partitions of Selected Devices Block
  block:
  - name: Insure Swap Partitions are Not Used
    command: "swapoff --all"

  - name: Wipe filesystem and partition table information
    command: "wipefs --all --force {{ item }}"
    loop: 
      "{{ disk_by_id }}"

  - name: Wait for kernel notification of changes to be processed
    command: "udevadm settle"

  - name: Notify Kernel of Updated Partitions
    command:
      "partprobe"
    when:
      - disable_partprobe|default(false)|bool == false

  when:
    ansible_nodename != "localhost"
  tags:
    - clear_partition_tables_from_devices
###############################################################################