---
###[ Create Disk Partitions ]##################################################
- name: Create Disk Partitions Block
  block:
  # This is created for UEFI or BIOS booting
  - name: Create UEFI Boot Loader Partitions 
    command: 
      "sgdisk {{ uefi_partition_flags }} {{ item }}"
    loop: 
      "{{ disk_by_id }}"
    loop_control:
      label: "{{ disk_by_id }}"

  # This is only created for legacy BIOS Booting only
  - name: Create BIOS Boot Loader Partitions for Legacy Boot
    command: 
      "sgdisk {{ bios_partition_flags }} {{ item }}"
    loop: 
      "{{ disk_by_id }}"
    loop_control:
      label: "{{ disk_by_id }}"
    when:
      - use_uefi_booting|default(false)|bool == false

  - name: Create SWAP Partitions
    command:
      "sgdisk {{(boot_pool_type == 'raidz')|ternary(raidz_multi_disk_swap_flags, single_disk_or_mirror_swap_flags)}} {{ item }}"
    loop: 
      "{{ disk_by_id }}"
    loop_control:
      label: "{{ disk_by_id }}"
    when:
      - enable_swap_partitions|default(true)|bool == true 

  - name: Create Boot Pool Partitions
    command:
      "sgdisk {{(boot_pool_type == 'raidz')|ternary(raidz_multi_disk_boot_partition_flags,single_disk_or_mirror_boot_partition_flags)}} {{ item }}"
    loop: 
      "{{ disk_by_id }}"
    loop_control:
      label: "{{ disk_by_id }}"

  - name: Create Root Pool Partitions
    command:
      "sgdisk {{ root_partition_flags }} {{ item }}"
    loop: 
      "{{ disk_by_id }}"
    loop_control:
      label: "{{ disk_by_id }}"

  - name: Notify Kernel of Updated Partitions
    command:
      "partprobe"
    when:
      - disable_partprobe|default(false)|bool == false
    
  when:
    ansible_nodename != "localhost"
  tags:
    - create_partitions
###############################################################################