---
# ##[ Create Disk Partitions ]##################################################

- name: Create Disk Partitions Block
  when:
    ansible_nodename != "localhost"
  tags:
    - create_partitions

  block:
    # This is created for UEFI booting
    - name: Create UEFI Boot Loader Partitions
      ansible.builtin.command:
        "sgdisk {{ uefi_partition_flags }} {{ item }}"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      loop:
        "{{ disk_by_id }}"
      when:
        - use_uefi_booting|default(false)|bool

    # This is only created for legacy BIOS Booting only
    - name: Create BIOS Boot Loader Partitions for Legacy Boot
      ansible.builtin.command:
        "sgdisk {{ bios_partition_flags }} {{ item }}"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      loop:
        "{{ disk_by_id }}"
      when:
        - not use_uefi_booting|default(false)|bool

    - name: Create SWAP Partitions
      ansible.builtin.command:
        "sgdisk {{ (boot_pool_type == 'raidz') | ternary(raidz_multi_disk_swap_flags, single_disk_or_mirror_swap_flags) }} {{ item }}"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      loop:
        "{{ disk_by_id }}"
      when:
        - enable_swap_partitions|default(true)|bool

    - name: Create Root Pool Partitions
      ansible.builtin.command:
        "sgdisk {{ root_partition_flags }} {{ item }}"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      loop:
        "{{ disk_by_id }}"

    - name: Notify Kernel of Updated Partitions
      ansible.builtin.command:
        "partprobe"
      when:
        - not disable_partprobe|default(false)|bool

###############################################################################
