---
# ##[ Create Disk Partitions ]##################################################

- name: Create Disk Partitions Block
  when:
    ansible_nodename != "localhost"
  tags:
    - create_partitions

  block:
    # This is created for UEFI booting
    - name: Create UEFI Boot Loader Partitions
      ansible.builtin.command:
        cmd: "sgdisk {{ uefi_partition_flags }} {{ item }}"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      loop:
        "{{ disk_by_id }}"
      when: disk_by_id | length | int == 1

    - name: Create EFI partition on first disk
      ansible.builtin.command:
        cmd: sgdisk {{ uefi_partition_flags }} {{ disk_by_id[0] }}
      register: cmd_first
      changed_when: cmd_first.rc == 0
      when: disk_by_id | length | int > 1

    - name: Get PARTUUID from first disk's EFI partition
      ansible.builtin.shell: >
        blkid -s PARTUUID -o value /dev/disk/by-partlabel/EFI
      register: boot_uuid
      changed_when: boot_uuid.rc == 0
      when: disk_by_id | length | int > 1

    - name: Create EFI partitions on remaining disks (using same PARTUUID)
      ansible.builtin.command: >
        sgdisk {{ uefi_partition_flags }}
                -u {{ boot_partition }}:{{ boot_uuid.stdout }}
                {{ item }}
      loop: "{{ disk_by_id[1:] }}"
      register: cmd_rest
      changed_when: cmd_rest.rc == 0
      when: disk_by_id | length | int > 1

    # # 1 or 2 devices = single or mirror flags, 3 or more use raid flags
    # - name: Create SWAP Partitions
    #   ansible.builtin.command:
    #     cmd: "sgdisk {{ (disk_by_id | length | int > 2) | ternary(raidz_multi_disk_swap_flags, single_disk_or_mirror_swap_flags) }} {{ item }}"
    #   register: cmd_output
    #   changed_when: cmd_output.rc == 0
    #   loop:
    #     "{{ disk_by_id }}"
    #   when:
    #     - enable_swap_partitions | default(true) | bool

    - name: Format LUKS partitions
      ansible.builtin.command:
        cmd: "sgdisk {{ luks_partition_flags }} {{ item }}"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      loop:
        "{{ disk_by_id }}"

    - name: Create Root Pool Partitions
      ansible.builtin.command:
        cmd: "sgdisk {{ root_partition_flags }} {{ item }}"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      loop:
        "{{ disk_by_id }}"

    - name: Wait for kernel notification of changes to be processed
      ansible.builtin.command:
        cmd: "udevadm settle"
      register: cmd_output
      changed_when: cmd_output.rc == 0

    - name: Pause for 5 seconds to settle
      ansible.builtin.pause:
        seconds: 5
