---
# [ Create Datasets for Filesystem ]###########################################
- name: Create Datasets for Filesystem Block
  when:
    - ansible_nodename != "localhost"
  tags:
    - create_datasets
  block:
    - name: Debug Datasets for Filesystem list
      ansible.builtin.debug:
        msg: "zfs create {{ item }}"
      loop:
        "{{ datasets_to_create }}"
      when: debug | default(false)

    - name: Create Datasets for Filesystem list
      ansible.builtin.command:
        "zfs create {{ item }}"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      loop:
        "{{ datasets_to_create }}"
      loop_control:
        label: "{{ item }}"

    # - name: Create Directories on mount points and set permissions
    #   ansible.builtin.file:
    #     state: directory
    #     path: "{{ mount_path.path }}"
    #     mode: "{{ mount_path.mode }}"
    #   loop:
    #     - { path: "{{ live_cd_mountpoint }}/root", mode: "700" }
    #     - { path: "{{ live_cd_mountpoint }}/var/tmp", mode: "1777" }
    #     - { path: "{{ live_cd_mountpoint }}/run/lock", mode: "755" }
    #     - { path: "{{ live_cd_mountpoint }}/etc/zfs", mode: "755" }
    #   loop_control:
    #     loop_var: mount_path
    #     label: "{{ mount_path.path }}"

    # - name: Mount run directory as tmpfs # noqa command-instead-of-module
    #   ansible.builtin.command:
    #     "mount -t tmpfs tmpfs {{ live_cd_mountpoint }}/run"
    #   register: cmd_output
    #   changed_when: cmd_output.rc == 0

    - name: Export and import ZFS
      ansible.builtin.command: "{{ item }}"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      loop:
        - zpool export {{ root_pool_name }}
        - zpool import -N -R {{ live_cd_mountpoint }} {{ root_pool_name }}
      loop_control:
        label: "{{ item }}"

    - name: Install python3-pexpect required by ansible.builtin.expect module
      ansible.builtin.apt:
        name: [python3-pexpect]
        state: present
        update_cache: true
        cache_valid_time: 3600

    - name: Load the FS ZFS with Encryption
      ansible.builtin.expect:
        command: zfs load-key -L prompt {{ root_pool_name }}
        responses:
          passphrase: "{{ passphrase }}"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      when:
        - root_pool_encryption | default(false)

    - name: Mount the Filesystem
      ansible.builtin.command:
        "{{ item }}"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      with_items:
        - "zfs mount {{ root_pool_dataset_path }}"
        - "zfs mount {{ root_pool_home_dataset_path }}/work"

    - name: Check mounts
      ansible.builtin.shell:
        cmd: set -o pipefail && mount | grep mnt
        executable: /bin/bash
      register: mount_output
      changed_when: false

    - name: Print mount_output.stdout
      ansible.builtin.debug:
        var: mount_output.stdout

    - name: Assert the ZFS mounts are present
      ansible.builtin.assert:
        that:
          - "root_pool_dataset_path + ' on /mnt' in mount_output.stdout"
          - "'on /mnt/home type zfs' in mount_output.stdout"

    - name: Update device symlinks
      ansible.builtin.command: udevadm trigger
      register: cmd_output
      changed_when: cmd_output.rc == 0

    - name: Installing a minimal linux system
      ansible.builtin.command:
        "debootstrap {{ distro_release }} {{ live_cd_mountpoint }}"
      register: cmd_output
      changed_when: cmd_output.rc == 0

# Removing zfs set devices=off
# See https://zfsonlinux.topicbox.com/groups/zfs-discuss/T6e36a82557df41e1
# https://wiki.archlinux.org/title/ZFS says:
# "Additionally, for security purposes, you may want to disable setuid and devices on the /tmp file system,
# which prevents some kinds of privilege-escalation attacks or the use of device nodes"
