- name: Install cryptsetup required by LUKS2 usage
  ansible.builtin.apt:
    name: [cryptsetup]
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Format to LUKS2 with same password
  ansible.builtin.shell:
    cmd: >
      set -o pipefail &&
      echo -n "{{ luks2_password }}" |
      cryptsetup luksFormat --type luks2 {{ item }}-part{{ luks_partition }} -
    executable: /bin/bash
  register: cmd_output
  changed_when: cmd_output.rc == 0
  loop:
    "{{ disk_by_id }}"

# Also possible: echo -n "This is pass1" | cryptsetup luksOpen /dev/sdb2 KEYSTORE0 -
- name: Unlock the LUKS2 partitions and map them
  ansible.builtin.expect:
    command: cryptsetup luksOpen {{ item }}-part{{ luks_partition }} KEYSTORE{{ index }}
    responses:
      passphrase: "{{ luks2_password }}"
  register: cmd_output
  changed_when: cmd_output.rc == 0
  loop:
    "{{ disk_by_id }}"
  loop_control:
    index_var: index

- name: Write zeros to the partition
  ansible.builtin.command:
    # Inside chroot {{ chroot_cmd }} bash -c '{{ item }}'
    cmd: dd if=/dev/zero of=/dev/mapper/KEYSTORE{{ index }} bs=1024M
  register: cmd_output
  changed_when: cmd_output.rc == 0
  failed_when: false
  loop:
    "{{ disk_by_id }}"
  loop_control:
    index_var: index

- name: Format to EXT4
  ansible.builtin.command:
    cmd: mkfs.ext4 /dev/mapper/KEYSTORE{{ index }}
  register: cmd_output
  changed_when: cmd_output.rc == 0
  loop:
    "{{ disk_by_id }}"
  loop_control:
    index_var: index

- name: Ensure primary directory for ZFS keys exists
  ansible.builtin.file:
    path: "{{ live_cd_mountpoint }}/etc/zfs/keys"
    state: directory
    mode: "0755"

- name: Ensure additional directories for ZFS keys exist
  ansible.builtin.file:
    path: "{{ live_cd_mountpoint }}/tmp/dir_luks2_{{ item_index }}"
    state: directory
    mode: "0755"
  loop: "{{ disk_by_id[1:] }}"
  loop_control:
    index_var: item_index
  when: disk_by_id | length | int > 1

# - name: Ensure directories for temporary mount exist for all drives
#   ansible.builtin.command:
#     cmd: "{{ chroot_cmd }} bash -c 'for i in $(seq 1 {{ disk_by_id | length }}); do mkdir -p /tmp/dir$i; done'"
#   register: cmd_output
#   changed_when: cmd_output.rc == 0

- name: Mount primary LUKS2 partition inside the chroot
  ansible.builtin.command:
    cmd: "{{ chroot_cmd }} bash -c 'mount /dev/mapper/KEYSTORE0 /etc/zfs/keys'"
  register: cmd_output
  changed_when: cmd_output.rc == 0

- name: Mount additional LUKS2 partitions inside the chroot
  ansible.builtin.command:
    cmd: "{{ chroot_cmd }} bash -c 'mount /dev/mapper/KEYSTORE{{ item_index }} /tmp/dir_luks2_{{ item_index }}'"
  register: cmd_output
  changed_when: cmd_output.rc == 0
  loop: "{{ disk_by_id[1:] }}"
  loop_control:
    index_var: item_index
  when: disk_by_id | length | int > 1

# Generate a long passphrase & Save it to the ZFS encryption dataset
- name: Generate and save the LUKS2 unlock key
  ansible.builtin.shell:
    cmd: >
        set -o pipefail &&
        (tr -dc '[:alnum:]' </dev/urandom | head -c64) || true > {{ live_cd_mountpoint }}/etc/zfs/keystore-luks2.key &&
        chmod 600 {{ live_cd_mountpoint }}/etc/zfs/keystore-luks2.key
    creates: "{{ live_cd_mountpoint }}/etc/zfs/keystore-luks2.key"
    executable: /bin/bash
  register: cmd_output
  changed_when: cmd_output.rc == 0

- name: Add key to LUKS2 partitions
  ansible.builtin.expect:
    command: cryptsetup luksAddKey {{ item }}-part{{ luks_partition }} {{ live_cd_mountpoint }}/etc/zfs/keystore-luks2.key
    responses:
      passphrase: "{{ luks2_password }}"
  loop:
    "{{ disk_by_id }}"

- name: Update /etc/crypttab for KEYSTORE
  ansible.builtin.copy:
    dest: "{{ live_cd_mountpoint }}/etc/crypttab"
    mode: "0644"
    content: |
      # <target name>  <source device>                    <key file>                    <options>
      KEYSTORE0        /dev/disk/by-partlabel/KEYSTORE    /etc/zfs/keystore-luks2.key   timeout=60

- name: Update /etc/fstab for KEYSTORE
  ansible.builtin.copy:
    dest: "{{ live_cd_mountpoint }}/etc/fstab"
    mode: "0644"
    content: |
      # <device>             <dir>           <type>  <options>  <dump>  <fsck>
      PARTLABEL=EFI          /boot/efi       vfat    defaults   0       0
      /dev/mapper/KEYSTORE0  /etc/zfs/keys   ext4    defaults   0       2
