- name: Copy ZFS key to primary permanent location
  ansible.builtin.copy:
    src: /etc/zfs/zroot.key
    remote_src: true
    dest: "{{ live_cd_mountpoint }}/etc/zfs/keys/zroot.key"
    mode: "000"

- name: Copy ZFS key to temporary locations for additional disks
  ansible.builtin.copy:
    src: /etc/zfs/zroot.key
    remote_src: true
    dest: "{{ live_cd_mountpoint }}/tmp/dir_luks2_{{ item_index }}/zroot.key"
    mode: "000"
  loop: "{{ disk_by_id[1:] }}"
  loop_control:
    index_var: item_index
  when: disk_by_id | length | int > 1

- name: Remove the zfs key password
  ansible.builtin.file:
    path: /etc/zfs/zroot.key
    state: absent

- name: Update ZFS key location
  ansible.builtin.command:
    cmd: zfs set keylocation="file:///etc/zfs/keys/zroot.key" {{ root_pool_name }}
  register: cmd_output
  changed_when: cmd_output.rc == 0

- name: Create dracut configuration for ZFS
  ansible.builtin.copy:
    dest: "{{ live_cd_mountpoint }}/etc/dracut.conf.d/zol.conf"
    mode: "0644"
    content: |
      nofsck="yes"
      add_dracutmodules+=" zfs "
      omit_dracutmodules+=" btrfs "
      install_items+=" /etc/zfs/keys/zroot.key "

- name: Re-build the initramfs with the ZFS key
  ansible.builtin.command:
    cmd: "{{ chroot_cmd }} bash -c 'dracut --regenerate-all -f'"
  register: cmd_output
  changed_when: cmd_output.rc == 0
