---
# [ Install ZFS and Kernel ]###################################################
# If optional kernel hardware enablement feature is enabled, will be used here.

- name: Install ZFS into chroot Block
  when:
    - ansible_nodename != "localhost"
  tags:
    - install_zfs
  block:
  # TO see progress ssh & run:
  # tail --lines=20 -f /mnt/var/log/apt/history.log
  # tail --lines=20 -f /mnt/var/log/apt/term.log
    - name: Install ZFS into chroot
      ansible.builtin.command:
        cmd: "{{ chroot_cmd }} bash -c '{{ item }}'"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      with_items:
        - apt-get -qq update
        - apt-get install --yes --no-install-recommends software-properties-common debconf-utils zstd
        # - apt-get install --yes --no-install-recommends linux-headers-$(uname -r) # Already part of linux-headers-amd64?
        - DEBIAN_FRONTEND=noninteractive apt-get install --yes --no-install-recommends linux-headers-amd64 linux-image-amd64 zfsutils-linux
        - apt-get install --yes --no-install-recommends dracut zfs-dracut dosfstools
        - apt-get install --yes --no-install-recommends wget nano vim
        # packages for LUK2
        - apt-get install --yes --no-install-recommends cryptsetup
      environment:
        DEBIAN_FRONTEND: noninteractive

    # The "old" kernel links mess up zfsbootmenu generation, so remove them
    # Don't need them for an initial install anyway
    - name: Clean up old kernel links
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      loop:
        - "{{ live_cd_mountpoint }}/boot/vmlinuz.old"
        - "{{ live_cd_mountpoint }}/boot/initrd.img.old"

    - name: Enable systemd ZFS services
      ansible.builtin.command:
        cmd: "{{ chroot_cmd }} bash -c '{{ item }}'"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      with_items:
        - systemctl enable zfs.target zfs-import-cache zfs-mount zfs-import.target
