---
###[ Add GRUB to fstab File for Single Device Configuration ]##################
- name: Add GRUB to fstab for Single Device Config Block
  block:
  # Some tasks that are only performed on single disk configurations
  - name: Run chroot commands to Configure GRUB on single disk only
    command:
      cmd: "{{chroot_cmd}} bash -c '{{item}}'"
      warn: no
    with_items:
      - "mkdir -p /boot/efi/grub /boot/grub"
      - "echo /boot/efi/grub /boot/grub none defaults,bind 0 0 >> /etc/fstab"
      - "mount /boot/grub"
  when:
    - ansible_nodename != "localhost"
    - disk_by_id|length == 1
  tags:
    - config_grub
###############################################################################

###[ GRUB Installation Process ]###############################################
- name: GRUB Installation Block
  block:
  # Parameters added to prevent grub menu selection for legacy devices
  - name: Run chroot command to install GRUB, Linux and ZFS for Legacy BIOS Booting
    command: "{{chroot_cmd}} /usr/bin/env DEBIAN_FRONTEND=noninteractive apt --yes -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' install grub-pc linux-image-generic zfs-initramfs zsys"
    when:
      - use_uefi_booting|default(false)|bool == false
    
  - name: Run chroot command to install GRUB, Linux and ZFS for UEFI Booting
    command: "{{chroot_cmd}} /usr/bin/env DEBIAN_FRONTEND=noninteractive apt --yes install grub-efi-amd64 grub-efi-amd64-signed linux-image-generic shim-signed zfs-initramfs zsys"
    when:
      - use_uefi_booting|default(false)|bool == true
  when:
    - ansible_nodename != "localhost"
    - ansible_os_family == "Debian"
  tags:
    - config_grub
###############################################################################

###[ Remove os-prober ]########################################################
# os-prober is only needed on dual-boot systems.
- name: Removing os-prober
  command: "{{chroot_cmd}} bash -c 'dpkg --purge os-prober'"
  when:
    - remove_os_prober|default(false)|bool == true
  tags:
    - config_grub
###############################################################################

###[ Set Root Password ]#######################################################
- name: Run chroot command to set default root password
  expect:
    command: "{{chroot_cmd}} passwd"
    responses:
      (?i)password: "{{ default_root_password }}"
  tags:
    - config_grub
###############################################################################
