# [ Install rEFInd Boot Manager latest version from official website ]##############################################

# Docs ZBM say to do BEFORE:
# mount -t efivarfs efivarfs /sys/firmware/efi/efivars
# ln -s /proc/self/mounts /etc/mtab

- name: Run chroot command to install all refind & SecureBoot dependencies
  ansible.builtin.command:
    cmd: "{{ chroot_cmd }} bash -c 'apt-get install --yes sbsigntool shim-signed mokutil curl'"
  register: cmd_output
  changed_when: cmd_output.rc == 0
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Download refind deb file
  ansible.builtin.get_url:
    url: https://sourceforge.net/projects/refind/files/0.14.2/refind_0.14.2-1_amd64.deb/download
    dest: "{{ live_cd_mountpoint }}/tmp/refind_0.14.2-1_amd64.deb"
    mode: "0644"
    # TODO use var  "{{ refind_deb_checksum }}"
    checksum: sha256:99265021489b18adfb0f4ac09c9032fb6042deeab2ee4497e8f22b58440cd4fe
  changed_when: false

- name: Install refind
  ansible.builtin.command:
    cmd: "{{ chroot_cmd }} bash -c '{{ item }}'"
  register: cmd_output
  changed_when: cmd_output.rc == 0
  with_items:
    # Mount required for mokutil --sb-state usage also
    - mount -t efivarfs efivarfs /sys/firmware/efi/efivars
    - dpkg -i /tmp/refind_0.14.2-1_amd64.deb
    - refind-install --yes --localkeys --shim /usr/lib/shim/shimx64.efi.signed
    - rm -rf /boot/refind_linux.conf
  environment:
    DEBIAN_FRONTEND: noninteractive

# https://github.com/Adito5393/SyncDiskPart
- name: Download SyncDiskPart
  ansible.builtin.get_url:
    url: https://packages.medo64.com/deb/dists/stable/main/binary-all/syncbootpart_1.0.0_all.deb
    dest: "{{ live_cd_mountpoint }}/tmp/syncbootpart_1.0.0_all.deb"
    mode: "0644"
    # TODO use var  "{{ syncbootpart_deb_checksum }}"
    checksum: sha256:801b9789c92a818540d81398275e16369a2ec192a41deaf5ae986d3473889c3d
  changed_when: false
  when: disk_by_id | length | int > 1

- name: Install SyncDiskPart aka syncbootpart
  ansible.builtin.command:
    cmd: "{{ chroot_cmd }} bash -c '{{ item }}'"
  register: cmd_output
  changed_when: cmd_output.rc == 0
  with_items:
    - DEBIAN_FRONTEND=noninteractive dpkg -i /tmp/syncbootpart_1.0.0_all.deb
  when: disk_by_id | length | int > 1

- name: Remove custom medo64 deb source
  ansible.builtin.file:
    path: "{{ live_cd_mountpoint }}/etc/apt/sources.list.d/medo64.list"
    state: absent
  when: disk_by_id | length | int > 1
