- name: Delete found MOK files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ live_cd_mountpoint }}/var/lib/dkms/mok.key"
    - "{{ live_cd_mountpoint }}/var/lib/dkms/mok.pub"

- name: Add MOK DKMS config
  ansible.builtin.copy:
    dest: "{{ live_cd_mountpoint }}/etc/dkms/framework.conf.d/mok_refind_local.conf"
    content: |
        mok_signing_key="/etc/refind.d/keys/refind_local.key"
        mok_certificate="/etc/refind.d/keys/refind_local.crt"
    mode: "0644"
    owner: root

- name: Comment out mok_signing_key
  ansible.builtin.lineinfile:
    path: "{{ live_cd_mountpoint }}/etc/dkms/framework.conf"
    regexp: '^mok_signing_key='
    line: '# mok_signing_key="/etc/refind.d/keys/refind_local.key"'
    create: false

- name: Comment out mok_certificate
  ansible.builtin.lineinfile:
    path: "{{ live_cd_mountpoint }}/etc/dkms/framework.conf"
    regexp: '^mok_certificate='
    line: '# mok_certificate="/etc/refind.d/keys/refind_local.crt"'
    create: false

- name: Install refind
  ansible.builtin.command:
    cmd: "{{ chroot_cmd }} bash -c '{{ item }}'"
  register: cmd_output
  changed_when: cmd_output.rc == 0
  with_items:
    - dpkg -i /tmp/refind_0.14.2-1_amd64.deb
    - refind-install --yes --localkeys --shim /usr/lib/shim/shimx64.efi.signed
    - rm -rf /boot/refind_linux.conf
