---
# [ Install rEFInd Boot Manager ]##############################################
- name: Install rEFInd Boot Manager Block
  when:
    - ansible_nodename != "localhost"
  tags:
    - install_refind
  block:
    - name: Run chroot command to install rEFInd Boot Manager
      ansible.builtin.command:
        cmd: "{{ chroot_cmd }} bash -c '{{ item }}'"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      with_items:
        - "DEBIAN_FRONTEND=noninteractive apt-get install --yes refind"
        - "refind-install"
        - "mkdir -p /boot/efi/EFI/zfsbootmenu"
      when:
        - ansible_os_family == "Debian"

    - name: Copy rEFInd template to /mnt/boot/efi/EFI/zfsbootmenu/refind_linux.conf
      ansible.builtin.template:
        src: refind_linux.conf.j2
        dest: "{{ live_cd_mountpoint }}/boot/efi/EFI/zfsbootmenu/refind_linux.conf"
        owner: "root"
        group: "root"
        mode: "0644"

    # If we're running under legacy bios then rEFInd will be installed
    # to /boot/efi/EFI/BOOT - we want it in /boot/efi/EFI/refind
    - name: Run chroot command to Move rEFInd if under Legacy BIOS
      ansible.builtin.command:
        cmd: "{{ chroot_cmd }} bash -c '{{ item }}'"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      with_items:
        - "[ -e /boot/efi/EFI/BOOT ] && mvrefind /boot/efi/EFI/BOOT /boot/efi/EFI/refind"
      when:
        - not use_uefi_booting|default(false)|bool

    - name: Reduce rEFIND boot menu timeout from 20 seconds to 10
      ansible.builtin.replace:
        path: "{{ live_cd_mountpoint }}/boot/efi/EFI/refind/refind.conf"
        regexp: '^timeout .*'
        replace: 'timeout {{ refind_boot_menu_timeout }}'

    - name: Copy startup script with multiple disks template to /mnt/boot/efi/startup.nsh
      ansible.builtin.template:
        src: startup.nsh.j2
        dest: "{{ live_cd_mountpoint }}/boot/efi/startup.nsh"
        owner: "root"
        group: "root"
        mode: "0644"
      when:
        - disk_by_id | length | int > 1
