- name: Install ZFS Service Templates
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ live_cd_mountpoint }}/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - zpool-trim@.service   # ZFS zpool trim service
    - zpool-trim@.timer     # ZFS zpool trim service timer unit
    - zpool-scrub@.service  # ZFS zpool scrub service
    - zpool-scrub@.timer    # ZFS zpool scrub service timer unit

- name: Run chroot commands to enable ZFS Trim Services
  ansible.builtin.command:
    cmd: "{{ chroot_cmd }} bash -c '{{ item }}'"
  register: cmd_output
  changed_when: cmd_output.rc == 0
  with_items:
    - "systemctl enable zpool-trim@{{ root_pool_name }}.service"
    - "systemctl enable zpool-trim@{{ root_pool_name }}.timer"
    - zpool set autotrim=off {{ root_pool_dataset_path }}
  when:
    - zfs_pool_trim_systemd_service_enable | default( false) | bool

- name: Run chroot commands to enable ZFS Scrub Service
  ansible.builtin.command:
    cmd: "{{ chroot_cmd }} bash -c '{{ item }}'"
  register: cmd_output
  changed_when: cmd_output.rc == 0
  with_items:
    - "systemctl enable zpool-scrub@{{ root_pool_name }}.service"
    - "systemctl enable zpool-scrub@{{ root_pool_name }}.timer"
  when:
    - zfs_pool_scrub_systemd_service_enable | default( false) | bool
