- name: Install ZFS Service Templates
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ live_cd_mountpoint }}/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - zpool-trim@.service   # ZFS zpool trim service
    - zpool-trim@.timer     # ZFS zpool trim service timer unit
    - zpool-scrub@.service  # ZFS zpool scrub service
    - zpool-scrub@.timer    # ZFS zpool scrub service timer unit

- name: Update timezone setting
  ansible.builtin.command:
    cmd: "{{ chroot_cmd }} bash -c '{{ item }}'"
  register: cmd_output
  changed_when: cmd_output.rc == 0
  with_items:
    - timedatectl set-timezone {{ timezone_value }}
