- name: Copy over ssh dir with authorized_keys to chroot environment
  ansible.builtin.copy: # noqa risky-file-permissions
    src: /root/.ssh
    dest: "{{ live_cd_mountpoint }}/root/"
    owner: root
    group: root
    remote_src: true

- name: Run chroot command to set default root password
  ansible.builtin.expect:
    command: "{{ chroot_cmd }} bash -c 'passwd'"
    responses:
      (?i)password: "{{ default_root_password }}"

- name: Install network management (recommended for laptops)
  ansible.builtin.command:
    cmd: "{{ chroot_cmd }} bash -c '{{ item }}'"
  register: cmd_output
  changed_when: cmd_output.rc == 0
  environment:
    DEBIAN_FRONTEND: noninteractive
  with_items:
    - >
        apt-get --yes install \
          network-manager \
          wpasupplicant
  when: network_backend == "network_manager"

- name: Configure network using systemd-networkd
  ansible.builtin.import_tasks: 13_00_systemd_networkd.yml
  when:
    - network_backend == "systemd_networkd"
