- name: Copy over ansible ssh key to chroot environment
  ansible.builtin.copy: # noqa risky-file-permissions
    src: "/root/.ssh"
    dest: "{{ live_cd_mountpoint }}/root/"
    owner: root
    group: root
    remote_src: true

- name: Run chroot command to set default root password
  ansible.builtin.expect:
    command: "{{ chroot_cmd }} bash -c 'passwd'"
    responses:
      (?i)password: "{{ default_root_password }}"
  no_log: "{{ no_log_secrets | default(true) }}"
