---
###[ Unmount chroot ]##############################################
- name: Prepare for First Reboot Block
  block:

  # Issue trying to get everything unmounted cleanly
  # https://github.com/openzfs/openzfs-docs/issues/270
  - name: Unmount chroot file systems
    shell: |
      mount | grep -v zfs | tac | awk '/\/mnt/ {print $3}' | xargs -i{} umount -lf {}
      umount /mnt/*
      umount -R /mnt
      umount -l /mnt
      grep /mnt /proc*/mounts | tac | awk '{print $3}' FS="/" | uniq | xargs -i{} kill -9 {}
    args:    
      warn: false      
    ignore_errors: yes

  - name: Export all ZFS Pools
    command: 
      "zpool export -a"

  when:
    - ansible_nodename != "localhost"
  tags:
    - unmount_chroot
