---
###[ Prepare for First Reboot ]##############################################
- name: Prepare for First Reboot Block
  block:
  - name: Run chroot command to install SSH Server and python3
    command: 
      "{{chroot_cmd}} bash -c 'apt install --yes openssh-server python3 python3-apt'"
    when:
      - ansible_os_family == "Debian"

  - name: Run chroot command add ansible user account (password disabled)
    command: 
      "{{chroot_cmd}} bash -c 'adduser {{ ansible_user }} --disabled-password --gecos Ansible_User'"
    args:
      creates: "/mnt/home/{{ ansible_user }}"

  - name: Copy over ansible sudoers include file to chroot environment
    copy:
      src: "{{sudoers_include_file}}"
      dest: "/mnt/{{sudoers_include_file}}"
      remote_src: yes

  - name: Copy over ansible ssh key to chroot environment
    copy:
      src: /home/{{ ansible_user }}/.ssh
      dest: /mnt/home/{{ ansible_user }}/
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      remote_src: yes

  - name: Copy create user script to /root
    template:
      src: add_user.j2
      dest: /mnt/root/add_user.sh
      owner: root
      group: root
      mode: '0700'

  # This script documents all the partition flags and sizes used in case needed for drive
  # replacement in the future.
  - name: Generate Partition Helper Script in  /root/partition_drive_helper.sh
    template:
      src: partition_drive_helper.j2
      dest: /mnt/root/partition_drive_helper.sh
      owner: root
      group: root
      mode: '0700'

  - name: Unmount chroot file systems
    shell: 
      cmd: "mount | grep -v zfs | tac | awk '/\\/mnt/ {print $3}' | xargs -i{} umount -lf {}"
      warn: false

  - name: Export all ZFS Pools
    command: 
      "zpool export -a"

  when:
    - ansible_nodename != "localhost"
  tags:
    - first_boot_prep
###############################################################################
