---
###[ Disable IPv6 Networking ]#################################################
- name: Disable IPv6 Networking Block
  block:
  - name: Disable IPv6 Networking
    ansible.builtin.lineinfile:
      path: "{{ipv6.conf_file}}"
      line: "{{item}}"
      state: present
    loop: "{{ipv6.disable_settings}}"
    loop_control:
      label: "{{item}}"
  
  - name: Apply Updated IPv6 Setting
    command: "{{ipv6.apply_cmd}}"
    
  when:
    - ipv6.disable|default(false)|bool == true
    - ansible_nodename != "localhost"
  tags:
    - disable_ipv6

###############################################################################
