---
# See: https://www.pbworks.net/ubuntu-guide-dropbear-ssh-server-to-unlock-luks-encrypted-pc/
# See: https://hamy.io/post/0009/how-to-install-luks-encrypted-ubuntu-18.04.x-server-and-enable-remote-unlocking/#gsc.tab=0
# See: https://github.com/dynerose/Remote-unlock-native-ZFS/blob/master/crypt_unlock.sh

- name: Configure System for Dropbear and Busybox to allow Remote Unlock Block
  block:
    # Possible the boot pool is not imported, make sure all is good
    - name: Make sure /boot/grub/grub.cf file is accessible
      stat:
        path: "/boot/grub/grub.cfg"
      register: grub_cfg
    
    - name: try to import boot pool if /boot/grub/grub.cfg did not exist
      command: "zpool import {{boot_pool_name}}"
      when: not grub_cfg.stat.exists

    - name: Install Dropbear and BusyBox
      apt: 
        name: ['dropbear','busybox']
        state: present 
      when: 
        - ansible_os_family == "Debian"

    - name: Update Dropbear Configuration Settings
      ini_file:
        path: /etc/default/dropbear
        section:
        option: "{{ item.key }}"
        value: "{{ item.value }}"
        no_extra_spaces: yes
        mode: '0644'
        create: no
      loop: "{{ apply_dropbear_settings|dict2items }}"

    - name: Update Initramfs Settings
      ini_file:
        path: /etc/initramfs-tools/initramfs.conf
        section:
        option: "BUSYBOX"
        value: "y"
        no_extra_spaces: yes
        mode: '0644'
        create: no

    - name: Update Dropbear-Initramfs Settings
      ini_file:
        path: /etc/dropbear-initramfs/config
        section:
        option: "DROPBEAR_OPTIONS"
        value: '"-p {{apply_dropbear_settings.DROPBEAR_PORT|default("22")}} {{apply_dropbear_settings.DROPBEAR_EXTRA_ARGS|default("-s")}}"'
        no_extra_spaces: yes
        mode: '0644'
        create: no

    - name: Convert Dropbear Key to id_rsa
      command: "/usr/lib/dropbear/dropbearconvert dropbear openssh dropbear_rsa_host_key id_rsa"
      args:
        chdir: "/etc/dropbear-initramfs/"
        creates: "/etc/dropbear-initramfs/id_rsa"

    - name: Generate Dropbear id_rsa.pub
      shell: 'dropbearkey -y -f dropbear_rsa_host_key |grep "^ssh-rsa " > id_rsa.pub'
      args:
        chdir: "/etc/dropbear-initramfs/"
        creates: "/etc/dropbear-initramfs/id_rsa.pub"

    - name: Remove existing Dropbear authorized_keys File
      file: 
        path: "/etc/dropbear-initramfs/authorized_keys"
        state: absent

    - name: Copy Specified Local Public Keys to Generate Dropbear authorized_keys File
      shell: "echo {{dropbear_user_restriction}} {{item}} >> /etc/dropbear-initramfs/authorized_keys"
      with_file: "{{rsa_public_key_for_dropbear}}"

    - name: Set Permissions on Dropbear authorized_keys File
      file: 
        path: "/etc/dropbear-initramfs/authorized_keys"
        state: file
        mode: '0600'

    - name: Place DropBear Template for Remote Root Pool Unlock
      template:
        src: crypt_unlock.j2
        dest: /etc/initramfs-tools/hooks/crypt_unlock.sh 
        mode: 755
        force: yes

    - name: Update initramfs
      command: "update-initramfs -u -k all"

    - name: Running update-grub
      command: "update-grub"

    - name: Leave Dropbear Service Disabled after boot.
      service:
        name: dropbear
        state: stopped
        enabled: no

  when:
    - enable_dropbear_with_busybox_support|default(false)|bool == true
    - root_pool_encryption|default(false)|bool == true
  tags:
    - install_drop_bear

