- name: Enable and start services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - zpool-trim@{{ root_pool_name }}.service
    - zpool-trim@{{ root_pool_name }}.timer
    - zpool-scrub@{{ root_pool_name }}.service
    - zpool-scrub@{{ root_pool_name }}.timer
    - zfs-work-dir-mount.service

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Disable zfs auto trim
  ansible.builtin.command:
    cmd: "{{ item }}"
  register: cmd_output
  changed_when: cmd_output.rc == 0
  with_items:
    - zpool set autotrim=off {{ root_pool_name }}

- name: Update timezone setting
  ansible.builtin.command:
    cmd: timedatectl set-timezone {{ timezone_value }}
  register: cmd_output
  changed_when: cmd_output.rc == 0

- name: Gather DKMS status
  ansible.builtin.command:
    cmd: dkms status
  register: dkms_output
  changed_when: dkms_output.rc == 0

- name: Parse ZFS version from DKMS status
  ansible.builtin.set_fact:
    module_zfs_and_version: "{{ dkms_output.stdout | regex_search('zfs\\/([0-9.]+)') }}"
  changed_when: false

- name: Remove previous ZFS build
  ansible.builtin.command:
    cmd: dkms remove {{ module_zfs_and_version }} --all
  register: cmd_output
  changed_when: cmd_output.rc == 0
  when: module_zfs_and_version is not none

- name: Add ZFS build
  ansible.builtin.command:
    cmd: dkms add {{ module_zfs_and_version }}
  register: cmd_output
  changed_when: cmd_output.rc == 0
  when: module_zfs_and_version is not none

- name: Auto-install ZFS build
  ansible.builtin.command:
    cmd: dkms autoinstall
  register: cmd_output
  changed_when: cmd_output.rc == 0

- name: Install Nvidia driver
  when: install_nvidia_driver
  block:
    - name: Include modprobe configuration files for Nvidia driver
      ansible.builtin.copy:
        dest: /etc/dracut.conf.d/10-nvidia.conf
        content: |
          install_items+=" /etc/modprobe.d/nvidia-blacklists-nouveau.conf /etc/modprobe.d/nvidia.conf /etc/modprobe.d/nvidia-options.conf "
          omit_dracutmodules+=" plymouth "
          omit_drivers+=" amdgpu "
        owner: root
        group: root
        mode: "0644"

    # Maybe also amd64-microcode ?
    - name: Install the nvidia-driver package, plus the necessary firmware
      ansible.builtin.apt:
        name: [nvidia-driver, firmware-misc-nonfree, firmware-amd-graphics]
        state: present
        update_cache: true

    # cat /sys/module/nvidia_drm/parameters/modeset should output Y
    - name: Enable nvidia-drm modeset
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/nvidia-options.conf
        regexp: '^options nvidia-drm modeset'
        line: options nvidia-drm modeset=1
        create: false

# Automatically Triggered after/by nvidia-driver
- name: Re-build the initramfs with the ZFS module signed
  ansible.builtin.command:
    cmd: dracut --regenerate-all -f
  register: cmd_output
  changed_when: cmd_output.rc == 0
  when: not install_nvidia_driver

- name: Re-generate ZFS Boot Menu with ZFS signed
  ansible.builtin.command:
    cmd: generate-zbm --debug
  register: cmd_output
  changed_when: cmd_output.rc == 0
