---
####################################################################################################
# This script is for installing and configuring ZFS on Root from an Ubuntu Live CD.
#
# Usage: --extra-vars='{"disk_devices": [sda, sdb], host_name: "mynewpc", passphrase: "mys3cret"}
#
# The "disk_devices" specifies the devices to erase all partitions from and install ZFS filesystem on.
# The simple "sda" style references will be converted to "disk_by_id" references.
#
# If the required "disk_devices", or "host_name" is not specified, you will be prompted to enter it.
######################################################################################################

- include_role: 
      name: helper_tasks
      tasks_from: 01_test_virtualbox.yml
  tags:
    - always

 #####################################################################################################

- name: Include Task Files
  include_tasks: "{{task_names}}"
  tags: ["always"]
  loop:
    - 01_basic_checks.yml
    - 02_confirm_defaults.yml
    - 03_install_zfs_packages.yml
    - 04_clear_partition_tables.yml
    - 05_create_partitions.yml
    - 06_create_pools.yml
    - 07_create_filesystems.yml
    - 08_create_datasets.yml
    - 09_config_system.yml
    - 10_config_boot_filesystem.yml
    - 11_config_grub.yml
    - 12_config_swap.yml
    - 12-5_system_tweaks.yml
    - 13_install_grub.yml
    - 14_fix_filesystem_mount_order.yml
    - 15_first_boot_prep.yml
    - 15-5_unmount_chroot.yml
    - 16_restart_remote.yml
    - 16-5_grub_uefi_multi_disk.yml
    - 17_create_regular_user.yml
    - 18_full_software_install.yml
    - 18-5_disable_ipv6.yml
    - 19_restart_remote_final.yml
    - 20_enable_dropbear.yml
    - 21_final_cleanup.yml
  loop_control:
    loop_var: task_names

- include_role: 
    name: helper_tasks
    tasks_from: 02_update_sshd_settings.yml
  when:
    - update_sshd_settings|default(false)|bool == true
  tags:
    - update_sshd_settings
