---
####################################################################################################
# This script is for installing and configuring ZFS on Root from an Ubuntu Live CD.
#
# Usage: --extra-vars='{"disk_devices": [sda, sdb], host_name: "mynewpc", passphrase: "mys3cret"}
#
# The "disk_devices" specifies the devices to erase all partitions from and install ZFS filesystem on.
# The simple "sda" style references will be converted to "disk_by_id" references.
#
# If the required "disk_devices", or "host_name" is not specified, you will be prompted to enter it.
######################################################################################################

# [ Load up the secret files ]#####################################################################
- name: Include Secret Files
  ansible.builtin.include_vars: "{{ item }}"
  tags: ["always"]
  # Was introduced ONLY for SMTP msmtp-mailer Client https://galaxy.ansible.com/chriswayg/msmtp-mailer
  # See https://github.com/reefland/ansible-zfs_on_root/commit/e74541a4c75e40dba041809ad563ec663755084e#diff-2ae05bbbcd423727412667df6e14fd4050f6a16d4530f37a3d22e54ba86a428eR145
  when: msmtp.enabled | default(false) | bool
  loop:
    - secrets/main.yml
  no_log: "{{ no_log_secrets | default(true) }}"

- name: Include Task Files
  ansible.builtin.include_tasks: "{{ task_names }}"
  tags: ["always"]
  loop:
    - 01_test_virtualbox.yml
    - 01_basic_checks.yml
    - 02_confirm_defaults.yml
    - 03_install_zfs_packages.yml
    - 04_clear_partition_tables.yml
    - 05_create_partitions.yml
    - 06_create_pools.yml
    - 07_create_filesystems.yml
    - 08_create_datasets.yml
    - 09_config_system.yml
    - 10_install_zfs.yml
    - 10_1_config_luks2.yml
    - 10_2_move_zfs_key_to_luks2.yml
    - 11_config_boot_efi.yml
    - 12_1_install_refind.yml
    - 12_2_config_mok_signing_dkms.yml
    - 12_3_install_task_runner.yml
    - 12_4_install_zfsbootmenu_fido2.yml
    - 12_4_install_efi_tools.yml
    - 12_5_zfs_set_home.yml
    - 12_7-system_tweaks.yml
    - 13_0_first_boot_prep.yml
    - 15_unmount_chroot.yml
    - 16_restart_remote.yml
  loop_control:
    label: "{{ task_names }}"
    loop_var: task_names
