---
# ZFS package installs have failed due to "not yet valid" message. This ususally happens
# when time is not set correctly on the new system.  This happened often when virtualbox
# snapshot images were used.  Restarting timesyncd service forces time to be updated.

- name: Restarting timesync service under Virtualbox
  command: "systemctl restart systemd-timesyncd"
  when: 
    - ansible_os_family == "Debian"
    - virutal_box|default(false)|bool == true
  tags:
    - install-zfs-packages

- name: Install ZFS packages (assumes Live CD Environment)
  apt: 
    name: ['debootstrap','gdisk','python-pexpect','zfs-initramfs']
    state: present 
    update_cache: yes
  when: ansible_os_family == "Debian"
  tags:
    - install-zfs-packages