---
- name: Install ZFS packages (assumes Live CD Environment)
  apt: 
    name: ['debootstrap','gdisk','python-pexpect','zfs-initramfs']
    state: present 
    update_cache: yes
  when: ansible_os_family == "Debian"
  tags:
    - install-zfs-packages

- name: Copy update time script to Live CD Environment
  copy:
    src: update-time.sh
    dest: "/home/{{ansible_distribution|lower}}"
    mode: "0755"
  when: ansible_distribution == "Ubuntu"
  tags:
    - configure-system
