---
###[ Create Disk Partitions ]##################################################
- name: Create Disk Partitions Block
  block:
  - name: Create UEFI Boot Loader Partitions
    command: 
      "sgdisk {{ uefi_partition_flags }} {{ item }}"
    loop: 
      "{{ disk_by_id }}"
  
  - name: Create BIOS Boot Loader Partitions
    command: 
      "sgdisk {{ bios_partition_flags }} {{ item }}"
    loop: 
      "{{ disk_by_id }}"

  - name: Create SWAP Partitions
    command: 
      "sgdisk {{(disk_by_id|length == 1)|ternary(single_disk_swap_flags,multi_disk_swap_flags)}} {{ item }}"
    loop: 
      "{{ disk_by_id }}"
    when:
      - enable_swap_partitions|default(true)|bool == true 

  - name: Create Boot Pool Partitions
    command:
      "sgdisk {{ boot_partition_flags }} {{ item }}"
    loop: 
      "{{ disk_by_id }}"

  - name: Create Root Pool Partition
    command:
      "sgdisk {{ root_partition_flags }} {{ item }}"
    loop: 
      "{{ disk_by_id }}"

  when:
    ansible_nodename != "localhost"
  tags:
    - create_partitions
###############################################################################