---
# Create Filesystem Containers ---------------------------------------------------
- name: Debug Create Boot and Root Filesystem Dataset Container
  debug:
    msg: "{{item}}"
  with_items:
    - "zfs create {{boot_pool_container_options}}"
    - "zfs create {{root_pool_container_options}}"
  when:
    debug|default(false) == true
  tags:
    - create_filesystems

- name: Create Boot and Root Filesystem Dataset Container
  command:
    cmd: "{{item}}"
  when:
    - ansible_nodename != "localhost"
  with_items:
    - "zfs create {{boot_pool_container_options}}"
    - "zfs create {{root_pool_container_options}}"
  tags:
    - create_filesystems

# Create Filesystem Boot and Root Containers ---------------------------------
- name: Debug Create Boot and Root Filesystem
  debug:
    msg: "{{item}}"
  with_items:
    - "zfs create {{root_dataset_options}} -o com.ubuntu.zsys:last-used={{epoch.stdout}} {{root_pool_name}}/ROOT/{{distro_name}}_{{UUID.stdout}}"
    - "zfs mount {{root_pool_name}}/ROOT/{{distro_name}}_{{UUID.stdout}}"
    - "zfs create {{boot_dataset_options}} {{boot_pool_name}}/BOOT/{{distro_name}}_{{UUID.stdout}}"
    - "zfs mount {{boot_pool_name}}/BOOT/{{distro_name}}_{{UUID.stdout}}"
  when:
    debug|default(false) == true
  tags:
    - create_filesystems

- name: Create Boot and Root Filesystem
  command:
    cmd: "{{item}}"
  when:
    - ansible_nodename != "localhost"
  with_items:
    - "zfs create {{root_dataset_options}} -o com.ubuntu.zsys:last-used={{epoch.stdout}} {{root_pool_name}}/ROOT/{{distro_name}}_{{UUID.stdout}}"
    - "zfs mount {{root_pool_name}}/ROOT/{{distro_name}}_{{UUID.stdout}}"
    - "zfs create {{boot_dataset_options}} {{boot_pool_name}}/BOOT/{{distro_name}}_{{UUID.stdout}}"
    - "zfs mount {{boot_pool_name}}/BOOT/{{distro_name}}_{{UUID.stdout}}"
  tags:
    - create_filesystems
