---
###[ Create Datasets for Filesystem ]#########################################
- name: Create Datasets for Filesystem Block
  block:
  - name: Debug Datasets for Filesystem list
    debug:
      msg: "zfs create {{item}}"
    loop: 
      "{{ datasets_to_create }}"
    when:
      debug|default(false) == true

  - name: Create Boot and Root Filesystem
    command:
      cmd: "zfs create {{item}}"
    loop: 
      "{{ datasets_to_create }}"
  
  when:
    - ansible_nodename != "localhost"
  tags:
    - create_datasets
###############################################################################

###[ Create Grub Datasets ]####################################################
- name: Create Grub Dataset Block
  block:
  - name: Debug Create Grub Dataset only when root_pool_type is a mirror, raidz, raidz2, raidz3
    debug:
      msg: "zfs create {{grub_dataset_options}}"
    when:
      debug|default(false) == true

  - name: Create Grub Dataset only when root_pool_type is a mirror, raidz, raidz2, raidz3 (anything other than empty)
    command:
      "zfs create {{grub_dataset_options}}"
  when:
    - root_pool_type != ""
    - ansible_nodename != "localhost"
  tags:
    - create_datasets
###############################################################################

- name: Installing a minimal linux system
  command:
    "debootstrap {{ubuntu_release}} /mnt"
  when:
    - ansible_nodename != "localhost"
  tags:
    - create_datasets
