---
###[ Create Datasets for Filesystems ]#########################################
- name: Create Boot and Root Filesystems Block
  block:
  - name: Debug Create Boot and Root Filesystems list
    debug:
      msg: "{{item}}"
    with_items:
      - "zfs create {{srv_dataset_options}}"
      - "zfs create {{usr_dataset_options}}"
      - "zfs create {{usr_local_dataset_options}}"
      - "zfs create {{var_dataset_options}}"
      - "zfs create {{var_games_dataset_options}}"
      - "zfs create {{var_lib_dataset_options}}"
      - "zfs create {{var_lib_acc_dataset_options}}"
      - "zfs create {{var_lib_apt_dataset_options}}"
      - "zfs create {{var_lib_dpkg_dataset_options}}"
      - "zfs create {{var_lib_net_dataset_options}}"
      - "zfs create {{var_lib_docker_dataset_options}}"
      - "zfs create {{var_log_dataset_options}}"
      - "zfs create {{var_mail_dataset_options}}"
      - "zfs create {{var_snap_dataset_options}}"
      - "zfs create {{var_spool_dataset_options}}"
      - "zfs create {{var_www_dataset_options}}"
      - "zfs create {{userdata_dataset_options}}"
      - "zfs create {{userdata_root_dataset_options}}"
    when:
      debug|default(false) == true

  - name: Create Boot and Root Filesystems
    command:
      cmd: "{{item}}"
    with_items:
      - "zfs create {{srv_dataset_options}}"
      - "zfs create {{usr_dataset_options}}"
      - "zfs create {{usr_local_dataset_options}}"
      - "zfs create {{var_dataset_options}}"
      - "zfs create {{var_games_dataset_options}}"
      - "zfs create {{var_lib_dataset_options}}"
      - "zfs create {{var_lib_acc_dataset_options}}"
      - "zfs create {{var_lib_apt_dataset_options}}"
      - "zfs create {{var_lib_dpkg_dataset_options}}"
      - "zfs create {{var_lib_net_dataset_options}}"
      - "zfs create {{var_lib_docker_dataset_options}}"
      - "zfs create {{var_log_dataset_options}}"
      - "zfs create {{var_mail_dataset_options}}"
      - "zfs create {{var_snap_dataset_options}}"
      - "zfs create {{var_spool_dataset_options}}"
      - "zfs create {{var_www_dataset_options}}"
      - "zfs create {{userdata_dataset_options}}"
      - "zfs create {{userdata_root_dataset_options}}"
  
  when:
    - ansible_nodename != "localhost"
  tags:
    - create_datasets
###############################################################################

###[ Create Grub Datasets ]####################################################
- name: Create Grub Dataset Block
  block:
  - name: Debug Create Grub Dataset only when root_pool_type is a mirror, raidz, raidz2, raidz3
    debug:
      msg: "zfs create {{grub_dataset_options}}"
    when:
      debug|default(false) == true

  - name: Create Grub Dataset only when root_pool_type is a mirror, raidz, raidz2, raidz3 (anything other than empty)
    command:
      "zfs create {{grub_dataset_options}}"
  when:
    - root_pool_type != ""
    - ansible_nodename != "localhost"
  tags:
    - create_datasets
###############################################################################

- name: Installing a minimal linux system
  command:
    "debootstrap {{ubuntu_release}} /mnt"
  when:
    - ansible_nodename != "localhost"
  tags:
    - create_datasets
