---
###[ Create Boot Filesystem ]##################################################
- name: Create Boot Filesystem Block
  block:
  - name: Run chroot command to install dosfstool on Debian based hosts
    command:
      cmd: "{{chroot_cmd}} bash -c 'apt install --yes vim dosfstools'"
    when:
      - ansible_os_family == "Debian"

  - name: Run chroot command to create /boot/efi directory
    command: 
      "{{chroot_cmd}} bash -c 'mkdir -p /boot/efi'"

  - name: Run chroot command to create EFI filesystems on all "-part1" partitions
    command:
      cmd: "{{chroot_cmd}} bash -c 'mkdosfs -F 32 -s 1 -n EFI {{ item }}-part1'"
    loop: 
      "{{ disk_by_id }}"

  when:
    ansible_nodename != "localhost"
  tags:
    - config_boot_fs
###############################################################################

###[ Build up fstab file ]#####################################################
- name: Build fstab File Block
  block:
  # Debug Remove any existing /boot/efi references within chroot environment
  # Entries would only exist if this task had been run previously
  - name:  Remove any existing /boot/efi references from fstab
    replace:
      path: /mnt/etc/fstab
      regexp: '(?m)^/dev/disk/by-uuid/.*/boot/efi.*\n?'
      replace: ''

  - name: Remove UNCONFIGURED message in /etc/fstab
    blockinfile:
      path: /mnt/etc/fstab
      marker: "# UNCONFIGURED FSTAB FOR BASE SYSTEM"
      block: ""

  - name: Add EFI Filesystems to /etc/fstab
    shell:
      cmd: 
        echo /dev/disk/by-uuid/$(blkid -s UUID -o value "{{disk_by_id[0]}}-part1") /boot/efi vfat defaults 0 0 >>/mnt/etc/fstab
  
  - name: Debug get contents of chroot /etc/fstab
    command:
      cmd: cat /mnt/etc/fstab
    register: cmd_output
    when:
      debug|default(false) == true

  - name: Debug show contents of chroot /etc/fstab
    debug:
      var: cmd_output['stdout']
    when:
      debug|default(false) == true

  when:
    ansible_nodename != "localhost"
  tags:
    - config_boot_fs
###############################################################################

###[ Mount Boot Filesystem in chroot environment ]#############################
- name: Mount Boot Filesystem in chroot Environment Block
  block:

  # Mount /boot/efi directory in chroot environment
  - name: Run chroot command to mount /boot/efi directory
    command: "{{chroot_cmd}} bash -c 'mount /boot/efi'"

  when:
    ansible_nodename != "localhost"
  tags:
    - config_boot_fs
###############################################################################