---
###[ Enable /tmp using tmpfs ]##################################################
- name: Enable tmp directory using tmpfs Block
  block:
  - name: Setup /tmp to use tmpfs
    copy:
      src: /mnt/usr/share/systemd/tmp.mount
      dest: /mnt/etc/systemd/system/tmp.mount
      remote_src: yes

  - name: Run chroot command enable /tmp
    command:
      cmd: "{{chroot_cmd}} bash -c 'systemctl enable tmp.mount'"
  when:
    - ansible_nodename != "localhost"
  tags:
    - system_tweaks
###############################################################################

###[ Add System Groups ]#######################################################
- name: Add System Groups Block
  block:
  - name: Run chroot commands to add system groups
    command:
      cmd: "{{chroot_cmd}} bash -c '{{item}}'"
    with_items:
      - "addgroup --system lpadmin"
      - "addgroup --system lxd"
      - "addgroup --system sambashare"
  when:
    - ansible_nodename != "localhost"
  tags:
    - system_tweaks
###############################################################################

### [ Patch Dependency Loop ]##################################################
- name: Patch Dependency Loop Block
  block:
  - name: Install Packaged Needed to fetch and apply patch
    command: 
      "{{chroot_cmd}} bash -c 'apt install --yes --no-install-recommends curl patch'"
    when:
      - ansible_nodename != "localhost"
      - ansible_os_family == "Debian"

  # Per ZFS on Root Guide this will create error on Hunk#2- know issue, error will be ignored
  - name: Run chroot command to curl and apply patch for Bug#1875577 Encrypted Swap with ZFS
    shell:
      cmd: "{{chroot_cmd}} bash -c 'curl -s https://launchpadlibrarian.net/478315221/2150-fix-systemd-dependency-loops.patch | sed \"s|/etc|/lib|;s|\\.in$||\" | (cd / ; patch -p1)'"
    ignore_errors: yes
    
  when:
    - ansible_nodename != "localhost"
  tags:
    - system_tweaks
###############################################################################      