---
###[ Create Regular / Non-root User ]##########################################
- name: Create Regular User Block
  block:

  - name: Create ZFS data set for home directory of regular user
    command: >-
      zfs create -o com.ubuntu.zsys:bootfs-datasets={{root_pool_dataset_path}}
      -o canmount=on -o mountpoint=/home/{{regular_user_account}} 
      {{root_pool_name}}/USERDATA/{{regular_user_account}}_{{UUID.stdout}}

  - name: Create Regular User
    user:
      name: "{{regular_user_account}}"
      groups: "{{regular_user_groups}}"
      home: "/home/{{regular_user_account}}"
      password: "{{ regular_user_password|password_hash('sha512') }}"
      shell: "{{regular_user_shell}}"
      state: present

  - name: Create skeleton home directory structure
    copy:
      src: "/etc/skel/."
      dest: "/home/{{regular_user_account}}"
      owner: "{{regular_user_account}}"
      group: "{{regular_user_account}}"
      mode: "0700"
      remote_src: yes
 
  when:
    - ansible_nodename != "localhost"
  tags:
    - create_regular_user
###############################################################################
