---
###[ Second Reboot of Remote System ]##########################################
- name: Second Reboot of Remote System Block
  block:
  - pause:
      prompt: |
        ##########################################################
        # {{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }} will be rebooted.
        ##########################################################

        {% if root_pool_encryption|default(false)|bool == true %}
        When prompted for passphrase for {{root_pool_name}}:
        Enter Passphrase: {{passphrase}}
        {% endif %}

        After the reboot has completed, please try out the system.
        
        Login as the non-root account:

              Non-root Account: {{regular_user_account}}       
                      Password: {{regular_user_password}}

        NOTE: {% if command_line_only|default(false)|bool == true%}System will remain command-line only.{%else%}Reboot will include a full GUI Desktop Environment.{% endif %}


        Press ENTER to reboot {{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}

  - name: Commencing Reboot, will take a few minutes....
    reboot:
      pre_reboot_delay: 30
      reboot_timeout: 3600

  tags:
    - restart_remote_final
###############################################################################
