---
# If disk_devices to use not specified on command line fail playbook
- fail: 
    msg: "ERROR: This playbook requires --extra-vars='{\"disk_devices\": [sda,sdb]}'"
  when: 
    disk_devices is undefined
  tags:
    - basic_checks

# This playbook can never be run on localhost as it is destructive.
- fail:
    msg: "ERROR: This playbook can not be used on localhost."
  when:
    ansible_nodename == "localhost"
  tags:
    - basic_checks

# ZFS Native Encryption Passphrase must be 8 chars or longer
- fail:
    msg: "ERROR: ZFS passphase must be at least 8 characters."
  when:
    - passphrase is defined and passphrase|length <8

- set_fact:
    root_pool_encryption: true
  when: passphrase is defined
  tags:
    - basic_checks

- debug:
    msg: "NOTE: Passphase Supplied -- Root Pool Encryption Enabled"
  when: root_pool_encryption is true
  tags: 
    - basic_checks