---
- name: Clear Partition Table from Devices
  command:
    cmd: "sgdisk --zap-all {{ item }}"
  loop: 
    "{{ disk_by_id }}"
  when:
    ansible_nodename != "localhost"
  register:
     sgdisk_ouput
  tags:
    - clear_partition_tables_from_devices

# Fail if return code is not 0      
- name: Clear Partition Table Result Check 
  fail:
    msg: "The command ({{ item.cmd }}) did not have a 0 return code"
  when: item.rc != 0
  loop: "{{ sgdisk_ouput.results }}"
  tags:
    - clear_partition_tables_from_devices

# NOTE: It is possible partition changes can not be picked up by the kernel.  A message such as:
#    "Error: Partition(s) 3 on /dev/sda have been written, but we have been unable to inform the kernel of the change, 
#    probably because it/they are in use.  As a result, the old partition(s) will remain in use.  You should reboot 
#    now before making further changes.
#
# If this happens, only open is reboot. The step below tried to reload the partition table and failed.

- name: Reload Partition Tables
  command:
    cmd: "partprobe"
  when:
    ansible_nodename != "localhost"
  tags:
    - clear_partition_tables_from_devices