---
#- name: Create ZFS Boot Pool
#  vars:
#    pool_type: "{{ boot_pool_type[(disk_by_id|length)]|default(boot_pool_type['default']) }}"

#  debug:
#    msg: "zpool create {{ boot_pool_options|join(' ') }} {{pool_type}} {{ disk_by_id|join(boot_partition_name_suffix+' ')+boot_partition_name_suffix }}"
#  tags:
#    - create_pools

 #ZFS Boot Pool Creation work -------------------------------------------------
- name: Create ZFS Boot Pool
  vars:
    pool_type: "{{ boot_pool_type[(disk_by_id|length)]|default(boot_pool_type['default']) }}"
  command:
    cmd: "zpool create -f {{ boot_pool_options|join(' ') }} {{pool_type}} {{ disk_by_id|join(boot_partition_name_suffix+' ')+boot_partition_name_suffix+' ' }}"
  when:
    - ansible_nodename != "localhost"
  tags:
    - create_pools

#- name: Create ZFS Root Pool
#  vars:
#    pool_type: "{{ root_pool_type[(disk_by_id|length)]|default(root_pool_type['default']) }}"
#  debug:
#    msg: "zpool create {{ root_pool_options|join(' ') }} {{pool_type}} {{ disk_by_id|join(root_partition_name_suffix+' ')+root_partition_name_suffix+' ' }}"
#  tags:
#    - create_pools

- name: Copy Pool Create Command
  vars:
    pool_type: "{{ root_pool_type[(disk_by_id|length)]|default(root_pool_type['default']) }}"
  copy: 
    content: "zpool create {{ root_pool_options|join(' ') }} {{pool_type}} {{ disk_by_id|join(root_partition_name_suffix+' ')+root_partition_name_suffix+' ' }}"
    dest: /tmp/pool.txt
  tags:
    - create_pools

# ZFS Root Pool Creation work -------------------------------------------------
- name: Create ZFS Root Pool
  vars:
    pool_type: "{{ root_pool_type[(disk_by_id|length)]|default(root_pool_type['default']) }}"
  expect:
    command:
     "zpool create -f {{ root_pool_options|join(' ') }} {{pool_type}} {{ disk_by_id|join(root_partition_name_suffix+' ')+root_partition_name_suffix+' ' }}"
    responses:
      passphrase: "{{passphrase}}"
      again: "{{passphrase}}"
  when:
    - ansible_nodename != "localhost"
  tags:
    - create_pools
