---
- name: Debug Create ZFS Boot Pool
  debug:
    msg: "zpool create {{ boot_pool_options|join(' ') }} {{boot_pool_type}} {{ disk_by_id|join(boot_partition_name_suffix+' ')+boot_partition_name_suffix+' ' }}"
  when:
    debug is defined
  tags:
    - create_pools

- name: Create ZFS Boot Pool
  command:
    cmd: "zpool create -f {{ boot_pool_options|join(' ') }} {{boot_pool_type}} {{ disk_by_id|join(boot_partition_name_suffix+' ')+boot_partition_name_suffix+' ' }}"
  when:
    - ansible_nodename != "localhost"
  tags:
    - create_pools

- name: Debut Create ZFS Root Pool
  debug:
    msg: "zpool create {{ root_pool_options|join(' ') }} {{root_pool_type}} {{ disk_by_id|join(root_partition_name_suffix+' ')+root_partition_name_suffix+' ' }}"
  when:
    debug is defined
  tags:
    - create_pools

- name: Create ZFS Root Pool for Encryption
  expect:
    command:
     "zpool create -f {{ root_pool_options|join(' ') }} {{root_pool_type}} {{ disk_by_id|join(root_partition_name_suffix+' ')+root_partition_name_suffix+' ' }}"
    responses:
      passphrase: "{{passphrase}}"
      again: "{{passphrase}}"
  when:
    - ansible_nodename != "localhost"
    - root_pool_encryption is true
  tags:
    - create_pools

- name: Create ZFS Root Pool without Encrytpion
  command:
     cmd: "zpool create -f {{ root_pool_options|join(' ') }} {{root_pool_type}} {{ disk_by_id|join(root_partition_name_suffix+' ')+root_partition_name_suffix+' ' }}"
  when:
    - ansible_nodename != "localhost"
    - root_pool_encryption is false
  tags:
    - create_pools
