---
- name: Create zfs-list cache directory
  file:
    path: /mnt/etc/zfs/zfs-list.cache
    state: directory
    mode: '0755'
  when:
    - ansible_nodename != "localhost"
  tags:
    - fix_mount_order

- name: Create bpool cache file
  file:
    path: "/mnt/etc/zfs/zfs-list.cache/{{boot_pool_name}}"
    state: touch
    mode: '0644'
  when:
    - ansible_nodename != "localhost"
  tags:
    - fix_mount_order

- name: Create rpool cache file
  file:
    path: "/mnt/etc/zfs/zfs-list.cache/{{root_pool_name}}"
    state: touch
    mode: '0644'
  when:
    - ansible_nodename != "localhost"
  tags:
    - fix_mount_order

- name: Run chrooted command to create symbolic link zed
  command: "{{chroot_cmd}} bash -c 'ln -s /usr/lib/zfs-linux/zed.d/history_event-zfs-list-cacher.sh /etc/zfs/zed.d'"
  when:
    - ansible_nodename != "localhost"
  tags:
    - fix_mount_order

- name: Run chrooted command to start zed service
  command: "{{chroot_cmd}} bash -c 'zed -p /tmp/zed.pid'"
  when:
    - ansible_nodename != "localhost"
  tags:
    - fix_mount_order

- name: sleep 5 seconds for zed service to do its work
  wait_for:
    timeout: 5
  tags:
    - fix_mount_order

- name: Checking stats on bpool cache
  stat:
    path: "/mnt/etc/zfs/zfs-list.cache/{{boot_pool_name}}"
  register: filestat
  when:
    - ansible_nodename != "localhost"
  tags:
    - fix_mount_order

- name: Run chrooted command to attempt forced cache update, bpool cache was empty
  command: "{{chroot_cmd}} bash -c 'zfs set canmount=noauto {{boot_pool_name}}/BOOT/{{distro_name}}_{{UUID.stdout}}'"
  when:
    - ansible_nodename != "localhost"
    - filestat.stat.size|int == 0
  tags:
    - fix_mount_order

- name: Checking stats on rpool cache
  stat:
    path: "/mnt/etc/zfs/zfs-list.cache/{{root_pool_name}}"
  register: filestat
  when:
    - ansible_nodename != "localhost"
  tags:
    - fix_mount_order

- name: Run chrooted command to , attempt forced cache update, rpool cache was empty
  command: "{{chroot_cmd}} bash -c 'zfs set canmount=noauto {{root_pool_name}}/ROOT/{{distro_name}}_{{UUID.stdout}}'"
  when:
    - ansible_nodename != "localhost"
    - filestat.stat.size|int == 0
  tags:
    - fix_mount_order

- name: Run chrooted command to stop ZED service
  command: "{{chroot_cmd}} bash -c 'kill $(cat /tmp/zed.pid)'"
  when:
    - ansible_nodename != "localhost"
  tags:
    - fix_mount_order

- name: Remove chroot based mount references from bpool zfs-list.cache 
  replace:
    path: "/mnt/etc/zfs/zfs-list.cache/{{boot_pool_name}}"
    regexp: '(?m)/mnt/?'
    replace: '/'
  tags:
    - fix_mount_order

- name: Remove chroot based mount references from rpool zfs-list.cache 
  replace:
    path: "/mnt/etc/zfs/zfs-list.cache/{{root_pool_name}}"
    regexp: '(?m)/mnt/?'
    replace: '/'
  tags:
    - fix_mount_order
