---
- name: Install ZFS packages (assumes Live CD Environment)
  apt: 
    name: ['debootstrap','gdisk','python-pexpect','zfs-initramfs']
    state: present 
    update_cache: yes
  when: ansible_os_family == "Debian"
  tags:
    - install-zfs-packages
