---
- name: Install ZFS packages (assumes Live CD Environment)
  apt: 
    name: "{{ item }}"
    state: present 
    update_cache: yes
  when: ansible_os_family == "Debian"
  with_items:
    - debootstrap
    - gdisk
    - zfs-initramfs
  tags:
    - install-zfs-packages
