---
# This configuration is designed to Ubuntu 20.04, it is not backward compatible to older versions.

# Set swap size that makes sense
swap_partition_size: "2G"

# Define Pool Names
boot_pool_name: "bpool"
root_pool_name: "rpool"

# Define the boot pool type based on number of devices.
# If you want 3 devices to be a 3 way mirror enable it, etc.
# A raidz will be the default if more than 2 devices are used
set_boot_pool_type:
  1: ""
  2: "mirror"
#  3: "mirror"
#  4: "mirror"
  default: "raidz"

# Define the root pool type based on number of devices.
# If you want 3 devices to be a 3 way mirror enable it, etc.
# A raidz will be the default if more than 2 devices are used
# The "raidz" option can be changed if you understand what it does.
set_root_pool_type:
  1: ""
  2: "mirror"
#  3: "mirror"
#  4: "mirror"
  default: "raidz"
#  default: "raidz2"
#  default: "raidz3"

####### Nothing Below Here Needs to be Edited ############

# Ubuntu Release name
ubuntu_release: "focal"
distro_name: "ubuntu"

# Boot Partition Flags
uefi_partition_flags: "-n1:1M:+512M     -t1:EF00"
bios_partition_flags: "-a1 -n5:24K:2047 -t5:EF02"

# Possible SWAP Partition Flags based on one device or more
single_disk_swap_flags: "-n2:0:+{{ swap_partition_size }} -t2:8200"
multi_disk_swap_flags:  "-n2:0:+{{ swap_partition_size }} -t2:FD00"

# Define Boot Pool Partition Flags
boot_partition_flags: "-n3:0:+2G        -t3:BE00"

# Define Root Pool Partition Flags - for Unencrypted or ZFS native Encrytpion
root_partition_flags: "-n4:0:0          -t4:BF00"

# Define Pool Partition Suffixes
boot_partition_name_suffix: "-part3"
root_partition_name_suffix: "-part4"

# Enable native ZFS root pool encryption (default false) - This will be set to true when a passprhase 
# is specified as an extra variable.
root_pool_encryption: false

# Set the boot and root pool type based on number of devices given ("", "mirror", "raidz", etc.)
boot_pool_type: "{{set_boot_pool_type[(disk_by_id|length)]|default(set_boot_pool_type['default'])}}"
root_pool_type: "{{set_root_pool_type[(disk_by_id|length)]|default(set_root_pool_type['default'])}}"

# Define Boot Pool Options
boot_pool_options:
  - "-o ashift=12 -d"
  - "-o feature@async_destroy=enabled"
  - "-o feature@bookmarks=enabled"
  - "-o feature@embedded_data=enabled"
  - "-o feature@empty_bpobj=enabled"
  - "-o feature@enabled_txg=enabled"
  - "-o feature@extensible_dataset=enabled"
  - "-o feature@filesystem_limits=enabled"
  - "-o feature@hole_birth=enabled"
  - "-o feature@large_blocks=enabled"
  - "-o feature@lz4_compress=enabled"
  - "-o feature@spacemap_histogram=enabled"
  - "-o feature@zpool_checkpoint=enabled"
  - "-O acltype=posixacl -O canmount=off -O compression=lz4"
  - "-O devices=off -O normalization=formD"
  - "-O relatime=on -O xattr=sa"
  - "-O mountpoint=/boot -R /mnt {{boot_pool_name}}"

# Define Root Pool Options
root_pool_options:
  - "-o ashift=12{{' '+(root_pool_encryption|default(false)) | ternary(root_pool_encryption_options|join(' '), '') }}"
  - "-O acltype=posixacl -O canmount=off -O compression=lz4"
  - "-O dnodesize=auto -O normalization=formD -O relatime=on"
  - "-O xattr=sa -O mountpoint=/ -R /mnt {{root_pool_name}}"

# Define Root Pool Encryption Options
root_pool_encryption_options:
  - "-O encryption=aes-256-gcm"
  - "-O keylocation=prompt -O keyformat=passphrase"

# Define datasets to act as containers
boot_pool_container_options: "-o canmount=off -o mountpoint=none {{boot_pool_name}}/BOOT"
root_pool_container_options: "-o canmount=off -o mountpoint=none {{root_pool_name}}/ROOT"

# Define Fileystem Dataset Options
boot_dataset_options: "-o canmount=noauto -o mountpoint=/boot"
root_dataset_options: "-o canmount=noauto -o mountpoint=/ -o com.ubuntu.zsys:bootfs=yes"

boot_pool_dataset_path: "{{boot_pool_name}}/BOOT/{{distro_name}}_{{UUID.stdout}}"
root_pool_dataset_path: "{{root_pool_name}}/ROOT/{{distro_name}}_{{UUID.stdout}}"

srv_dataset_options: "-o com.ubuntu.zsys:bootfs=no {{root_pool_dataset_path}}/srv"
usr_dataset_options: "-o com.ubuntu.zsys:bootfs=no -o canmount=off {{root_pool_dataset_path}}/usr"
usr_local_dataset_options: "{{root_pool_dataset_path}}/usr/local"
var_dataset_options: "-o com.ubuntu.zsys:bootfs=no -o canmount=off {{root_pool_dataset_path}}/var"
var_games_dataset_options: "{{root_pool_dataset_path}}/var/games"
var_lib_dataset_options: "{{root_pool_dataset_path}}/var/lib"
var_lib_acc_dataset_options: "{{root_pool_dataset_path}}/var/lib/AccountsService"
var_lib_apt_dataset_options: "{{root_pool_dataset_path}}/var/lib/apt"
var_lib_dpkg_dataset_options: "{{root_pool_dataset_path}}/var/lib/dpkg"
var_lib_net_dataset_options: "{{root_pool_dataset_path}}/var/lib/NetworkManager"
var_lib_docker_dataset_options: "-o com.sun:auto-snapshot=false {{root_pool_dataset_path}}/var/lib/docker"
var_log_dataset_options: "{{root_pool_dataset_path}}/var/log"
var_mail_dataset_options: "{{root_pool_dataset_path}}/var/mail"
var_snap_dataset_options: "{{root_pool_dataset_path}}/var/snap"
var_spool_dataset_options: "{{root_pool_dataset_path}}/var/spool"
var_www_dataset_options: "{{root_pool_dataset_path}}/var/www"

userdata_dataset_options: "-o canmount=off -o mountpoint=/ {{root_pool_name}}/USERDATA"
userdata_root_dataset_options: "-o com.ubuntu.zsys:bootfs-datasets={{root_pool_dataset_path}} -o canmount=on -o mountpoint=/root {{root_pool_name}}/USERDATA/root_{{UUID.stdout}}"

grub_dataset_options: "{{boot_pool_dataset_path}}/grub"